In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]) # vektör oluşturduk
print(arr) # .shape , .size

[1 2 3 4 5]


In [3]:
arr2= np.array([[1,2],[3,4]])
print(arr2.shape)

(2, 2)


In [4]:
a = np.zeros((3,4)) # 0 'lar ile dolu , np.ones , np.random.random

a[0][0] = 1
a[0][1] = 2
a[2][1] = 5
print(a)

[[1. 2. 0. 0.]
 [0. 0. 0. 0.]
 [0. 5. 0. 0.]]


In [5]:
a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [6]:
a = np.linspace(10,50,20)
print(a)

[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]


In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a**2)
print(np.sin(a))

[5 7 9]
[-3 -3 -3]
[1 4 9]
[0.84147098 0.90929743 0.14112001]


In [8]:
print(a<2)

[ True False False]


In [9]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6]])


print(c*d)  # element wise product

[[ 1  4  9]
 [16 25 36]]


In [10]:
c.dot(d.T)

array([[14, 32],
       [32, 77]])

In [11]:
"""
print(c.sum())
print(c.max())
print(c.min())


print(c.sum(axis=0))
print(c.sum(axis=1))

print(np.sqrt(c))
print(np.square(c)) # a**2
print(np.add(a,a))
"""
print("")

In [12]:
array = np.array([1,2,3,4,5,6,7])   #  vector dimension = 1

print(array[0])

print(array[0:4])

reverse_array = array[::-1]
print(reverse_array)

1
[1 2 3 4]
[7 6 5 4 3 2 1]


In [13]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c[0,:])

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [14]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = array.ravel() #flatten
print(a)
array2 = a.reshape(3,3) # geri reshape
print(array2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a = np.array([1,2,3])

b = a
b[0] = 5
c = a
print(c)

[5 2 3]


In [16]:
d =  np.array([1,2,3])
e = d.copy()
e[0] = 5
print(d)

[1 2 3]


In [17]:
array3 = np.vstack((d,e)) # dikey
array4 = np.hstack((d,e)) # yatay
array4

array([1, 2, 3, 5, 2, 3])