In [2]:
import numpy as np

# NumPy Basics

In [19]:
# Creating an array.
array = np.array([1,3,5,7,9])

# Creating an range array.
array = range = np.arange(1,10)

# Creating an range array x by x.
array = np.arange(10,100,3)

# Creating an array of zeros for x times.
array = np.zeros(10)

# Creating an array of ones for x times.
array = np.ones(10) 

# Creating a range array y by y.
array = np.linspace(0,100,5)

# Creating a range array.
array = np.arange(50)

# Shaping the array to 5 rows and 10 columns.
array = array.reshape(5,10)

# Selecting randomly count of z values between x and y.
array = np.random.randint(10,100,6)

# Returns the array/matrix size.
array.ndim 

1

# Advanced Definitions

In [20]:
# Definition of a Vector.

vector = np.array([1,3,5,7,9])
print(f"VECTOR\n{vector}\nndim: {vector.ndim}")

# Definition of a Matrix.

matrix = np.array([[1,3,5,7,9],[11,13,15,17,19]])
print(f"\nMATRIX\n{matrix}\nndim: {matrix.ndim}")

# Definition of a Tensor.

tensor = np.array([[[0,2,4,6,8],[10,12,14,16,18]],[[1,3,5,7,9],[11,13,15,17,19]]])
print(f"\nTENSOR\n{tensor}\nndim: {tensor.ndim}")

VECTOR
[1 3 5 7 9]
ndim: 1

MATRIX
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
ndim: 2

TENSOR
[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[ 1  3  5  7  9]
  [11 13 15 17 19]]]
ndim: 3


# Reshaping and Fixing Arrays

In [21]:
# Variables.

v = np.array([1,2,3,4,5,6])
m = np.array([[1,2,3,4,5,6],[6,7,8,9,10,11]])
t = np.array([[[1,2,3,4,5,6],[6,7,8,9,10,11]],[[-1,-2,-3,-4,-5,-6],[-6,-7,-8,-9,-10,-11]]])

# Reshaping a vector.

v = v.reshape(3,2) # X * Y must be equal to total lenght of the vector!
print(f"Vector to Matrix\n{v}")

v = v.reshape(1,2,3) # X * Y must be equal to total lenght of the vector!
print(f"\nVector to Tensor\n{v}")

# Reshaping a matrix.

m = m.reshape(6,2) # X * Y must be equal to total lenght of the matrix!
print(f"\nMatrix to Matrix\n{m}")

m = m.reshape(3,2,2) # X * Y must be equal to total lenght of the matrix!
print(f"\nMatrix to Tensor\n{m}")

# Reshaping a tensor.

t = t.reshape(3,4,2) # X * Y must be equal to total lenght of the matrix!
print(f"\nTensor to Tensor\n{t}")

t = t.reshape(6,4) # X * Y must be equal to total lenght of the matrix!
print(f"\nTensor to Matrix\n{t}")

t = np.array(t.reshape(24,1).flatten(), ndmin=1) # X * Y must be equal to total lenght of the matrix!
print(f"\nTensor to Vector\n{t}")

Vector to Matrix
[[1 2]
 [3 4]
 [5 6]]

Vector to Tensor
[[[1 2 3]
  [4 5 6]]]

Matrix to Matrix
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 8  9]
 [10 11]]

Matrix to Tensor
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

Tensor to Tensor
[[[  1   2]
  [  3   4]
  [  5   6]
  [  6   7]]

 [[  8   9]
  [ 10  11]
  [ -1  -2]
  [ -3  -4]]

 [[ -5  -6]
  [ -6  -7]
  [ -8  -9]
  [-10 -11]]]

Tensor to Matrix
[[  1   2   3   4]
 [  5   6   6   7]
 [  8   9  10  11]
 [ -1  -2  -3  -4]
 [ -5  -6  -6  -7]
 [ -8  -9 -10 -11]]

Tensor to Vector
[  1   2   3   4   5   6   6   7   8   9  10  11  -1  -2  -3  -4  -5  -6
  -6  -7  -8  -9 -10 -11]


# Indexing the NumPy Arrays

In [22]:
# Creating a array like = [0 5 10 15 20]
numbers = np.arange(0,25,5)

# Input Parameter = Index Value, Output Parameter = Element.
result = numbers[4]

# Returns the last element of the array.
result = numbers[-1]

# Returns between a and b indexes.
result = numbers[0:3]

# Returns the whole array.
result = numbers[::]

# Returns the whole array three by three.
result = numbers[::3]

# Shows the x'th array's y'th element.
numberx = np.array([[0,1,2],[3,4,5]])
result = numberx[1,0]

print(result)

3


# Sort and Order Operations for NumPy Arrays

In [23]:
a = np.array([[1,9,5],[7,3,11]])

# Sort

print("Main Array:")
print(a)
print("\n")

print("After the sort() function:")
print(np.sort(a))
print("\n")

# Order

dt = np.dtype([("name", "S50"), ("age", int)])
a = np.array([("Beckham", 44),("Cristiano",36),("Xavi",41),("Iniesta",36)], dtype = dt)

print("Main Array:")
print(a)
print("\n")

print("Order by Age:")
print(np.sort(a, order="age"))
print("\n")

print("Order by Name:")
print(np.sort(a, order="name"))
print("\n")

Main Array:
[[ 1  9  5]
 [ 7  3 11]]


After the sort() function:
[[ 1  5  9]
 [ 3  7 11]]


Main Array:
[(b'Beckham', 44) (b'Cristiano', 36) (b'Xavi', 41) (b'Iniesta', 36)]


Order by Age:
[(b'Cristiano', 36) (b'Iniesta', 36) (b'Xavi', 41) (b'Beckham', 44)]


Order by Name:
[(b'Beckham', 44) (b'Cristiano', 36) (b'Iniesta', 36) (b'Xavi', 41)]




# Introduction to the NumPy Maths

In [24]:
# Mathematical Operators.

numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)

result = np.sin(numbers1)
result = np.cos(numbers1)
result = np.sqrt(numbers1)
result = np.log(np.array([2.7, 10])) # Log base defined for euler number.

print(result)

# Array Stacking.

mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

print(mnumbers1)
print(mnumbers2)

result = np.vstack((mnumbers1, mnumbers2))
result = np.hstack((mnumbers1, mnumbers2))

print(result)

# Mathematical Comparing.

result = numbers1 >= 50
print(numbers1[result])

[0.99325177 2.30258509]
[[53 70 48]
 [41 93 33]]
[[67 95 31]
 [13 46 80]]
[[53 70 48 67 95 31]
 [41 93 33 13 46 80]]
[53 70 93]


# NumPy Maths: Combine Operations

In [ ]:
# Variables.

vx = np.array([1,2,3,4,5])
vy = np.array([1,2,3,4,5])
mx = np.array([[1,2,3,4,5],[6,7,8,9,10]])
my = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tx = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])
ty = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])

# Array Combine.

def xcombine(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        x[i] += y[i]
    return x

# Matrix Combine.

def mcombine(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

# Tensor Combine.

def tcombine(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            for q in range(x.shape[2]):
                x[i,j,q] += y[i,j,q]
    return x

# Cross Variable Combine >>> Vector X Matrix.

def cvxcross(x,y):
    # X is Matrix.
    # Y is Vector.
    # Ndim Comprasion Always Have to be Like That: x > y.
    # Vector values added seperately to each matrix columns.
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

# Results for combining.

print(f"VX + VY\n{xcombine(vx,vy)}\nNdim: {vx.ndim}")
print(f"\nMX + MY\n{mcombine(mx,my)}\nNdim: {mx.ndim}")
print(f"\nTX + TY\n{tcombine(tx,ty)}\nNdim: {tx.ndim}")
print(f"\nMX + VX\n{cvxcross(mx,vx)}")

# NumPy Maths: Subtraction Operations

In [ ]:
# Variables.

vx = np.array([1,2,3,4,5])
vy = np.array([1,2,3,4,5])
mx = np.array([[1,2,3,4,5],[6,7,8,9,10]])
my = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tx = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])
ty = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])

# Array Subtract.

def xsub(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape):
        x[i] -= y[i]
    return x

# Matrix Subtract.

def msub(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] -= y[i,j]
    return x

# Tensor Subtract.

def tsub(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            for q in range(x.shape[2]):
                x[i,j,q] -= y[i,j,q]
    return x

def cvxcross(x,y):
    # X is Matrix.
    # Y is Vector.
    # Ndim Comprasion Always Have to be Like That : X > Y.
    # Vector values added seperately to each matrix columns.
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] -= y[j]
    return x

# Results

print(f"VX - VY\n{xsub(vx,vy)}\nNdim: {vx.ndim}")
print(f"\nMX - MY\n{msub(mx,my)}\nNdim: {mx.ndim}")
print(f"\nTX - TY\n{tsub(tx,ty)}\nNdim: {tx.ndim}")
print(f"\nMX - VX\n{cvxcross(mx,vx)}")

# NumPy Maths: Multiplication Operations

In [ ]:
# Variables.

vx = np.array([1,2,3,4,5])
vy = np.array([1,2,3,4,5])
mx = np.array([[1,2,3,4,5],[6,7,8,9,10]])
my = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tx = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])
ty = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])

# Array Multiply.

def xmultiply(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        x[i] *= y[i]
    return x

# Matrix Multiply.

def mmultiply(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] *= y[i,j]
    return x

# Tensor Multiply.

def tmultiply(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            for q in range(x.shape[2]):
                x[i,j,q] *= y[i,j,q]
    return x

def cvxcross(x,y):
    # X is Matrix.
    # Y is Vector.
    # Ndim Comprasion Always Have to be Like That : X > Y.
    # Vector values added seperately to each matrix columns.
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] *= y[j]
    return x

# Results

print(f"VX * VY\n{xmultiply(vx,vy)}\nNdim: {vx.ndim}")
print(f"\nMX * MY\n{mmultiply(mx,my)}\nNdim: {mx.ndim}")
print(f"\nTX * TY\n{tmultiply(tx,ty)}\nNdim: {tx.ndim}")
print(f"\nMX * VX\n{cvxcross(mx,vx)}")

# NumPy Maths: Division Operations

In [ ]:
# Variables.

vx = np.array([5,10,15,20,25])
vy = np.array([1,2,3,4,5])
mx = np.array([[5,10,15,20,25],[30,35,40,45,50]])
my = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tx = np.array([[[5,10,15,20,25],[30,35,40,45,50]],[[-5,-10,-15,-20,-25],[-30,-35,-40,-45,-50]]])
ty = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[-1,-2,-3,-4,-5],[-6,-7,-8,-9,-10]]])

# Array Divide.

def xdivide(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        x[i] /= y[i]
    return x

# Matrix Divide.

def mdivide(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] /= y[i,j]
    return x

# Tensor Divide.

def tdivide(x,y):
    assert len(x.shape)
    assert x.shape == y.shape

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            for q in range(x.shape[2]):
                x[i,j,q] /= y[i,j,q]
    return x

def cvxcross(x,y):
    # X is Matrix.
    # Y is Vector.
    # Ndim Comprasion Always Have to be Like That : X > Y.
    # Vector values added seperately to each matrix columns.
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] /= y[j]
    return x

# Results

print(f"VX / VY\n{xdivide(vx,vy)}\nNdim: {vx.ndim}")
print(f"\nMX / MY\n{mdivide(mx,my)}\nNdim: {mx.ndim}")
print(f"\nTX / TY\n{tdivide(tx,ty)}\nNdim: {tx.ndim}")
print(f"\nMX / VX\n{cvxcross(mx,vx)}")

# Crossproduct Operations Using NumPy

### Mathematical Proof is that:

##### v1 = [3,2,2]
##### v2 = [1,4,2]

##### CROSS(v1,v2) = [(2x2-4x2), -(3x2-1x2), (3x4-1x2)]
##### RESULT = [-4,-4,10]

In [26]:
import math

v1 = np.array([3,2,2])
v2 = np.array([1,4,2])

def ParallelogramArea(a,b):
    area = math.sqrt((a[1] * b[2] - b[1] * a[2]) ** 2 + (a[0] * b[2] - b[0] * a[2]) ** 2 + (a[0] * b[1] - b[0] * a[1]) ** 2)
    return area

print(f"V1 to V2 Cross Product\n{np.cross(v1,v2)}")
print(f"\nV2 to V1 Cross Product\n{np.cross(v2,v1)}")
print(f"\nArea of Parallelogram Made by V1/V2 Vectors\n{'%.2f' % ParallelogramArea(v1,v2)}")

V1 to V2 Cross Product
[-4 -4 10]

V2 to V1 Cross Product
[  4   4 -10]

Area of Parallelogram Made by V1/V2 Vectors
11.49
